### PR TITLE
Print newline after sif dump

### LINKED ISSUE #36: siftool dump should print newline after output
```
[vagrant@localhost tmp]$ siftool dump 2 alpine_latest.sif
{"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh"]}[vagrant@localhost tmp]$
```

### PR DESCRIPTION
**Pull request by sashayakovtseva**
Closes #36

### CODE REVIEW

**Comment by jmstover** [comment]
If I do... 
`siftool dump 1 lolcow.sif > lolcow.squashfs` 

Will this extra `fmt.Println()` mess up the `.squashfs` output? 

Also... there's a lot more changes than just that newline in this PR. =)

**Comment by sashayakovtseva** [comment]
@jmstover Yes, it will. Maybe I should check which data type is printed or whether stdout is tty?

**Comment by jmstover** [comment]
> @jmstover Yes, it will. Maybe I should check which data type is printed or whether stdout is tty?

I'd say datatype. If it returns `FsSquash` or `FsEncryptedSquashfs` then don't print the new line...  Or if there's a way to determine if the index given is a image partition?

**Comment by sashayakovtseva** [comment]
@jmstover Descriptor has a datatype, which looks to be enough to handle the case.
```
// List of supported SIF data types.
const (
	DataDeffile       Datatype = iota + 0x4001 // definition file data object
	DataEnvVar                                 // environment variables data object
	DataLabels                                 // JSON labels data object
	DataPartition                              // file system data object
	DataSignature                              // signing/verification data object
	DataGenericJSON                            // generic JSON meta-data
	DataGeneric                                // generic / raw data
	DataCryptoMessage                          // cryptographic message data object
)
```

How about printing new line if not `DataPartition`?

**Comment by jmstover** [comment]
> How about printing new line if not `DataPartition`?

That would probably be fine. I'm iffy about `DataGeneric` as that looks like it _could_ be data where an extra newline could throw it off as well.

**Comment by sashayakovtseva** [comment]
@jmstover Maybe we should not consider it a bug then?

**Comment by jmstover** [comment]
This is an output bug in certain cases. It just can't blindly add a newline as that will break other cases. For any JSON output, it should happen, so it looks like `DataLabels`, `DataGenericJSON`, and probably `DataDeffile` should have a new line at the least.

@jscook2345 ... Any thoughts?

**Comment by sashayakovtseva** [comment]
If this is a visual _output_ bug, then we should check for TTY, not for datatype IMO.

**Comment by jmstover** [comment]
Agree with that... For the data types I mentioned, an extra newline isn't going to make the output invalid. So, display or type it doesn't really matter. But `DataPartition` cannot have the newline at all otherwise it's invalid, possibly `DataGeneric`.

I don't know about `DataSignature`, or `DataCryptoMessage` as I don't know how that's stored, but I would guess a newline wouldn't break the Signature at least.

**Comment by sashayakovtseva** [comment]
@jscook2345 need your opinion.
IMO it is either TTY check, or closing PR and issue to prevent unexpected issues as @jmstover suggests (btw thanks for pointing them out!).

**Comment by WestleyK** [comment]
If you want my opinion, this should not print a newline. It should just output the actual data.

**Comment by sashayakovtseva** [comment]
@WestleyK I tend to think the same now

**Comment by jscook2345** [comment]
I think it's OK to close this and just stick with current behavior.

**Pull request closed without merging**
